name       : python-prompt-toolkit
version    : 3.0.5
release    : 5
source     :
    - https://github.com/prompt-toolkit/python-prompt-toolkit/archive/3.0.5.tar.gz : c40e2c3404f9929cbacd880b309099184bc4ffa200f6103e1d24d600005ec69c
homepage   : https://github.com/prompt-toolkit/python-prompt-toolkit
license    : BSD-3-Clause
component  : programming.python
summary    : Library for building powerful interactive command lines in Python
description: |
    Library for building powerful interactive command lines in Python
builddeps  :
    - pkgconfig(python3)
    - python-pytest
    - python-six
    - python-wcwidth
rundeps    :
    - python-six
    - python-wcwidth
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
