name       : python-prompt-toolkit
version    : 3.0.32
release    : 11
source     :
    - https://files.pythonhosted.org/packages/source/p/prompt_toolkit/prompt_toolkit-3.0.32.tar.gz : e7f2129cba4ff3b3656bbdda0e74ee00d2f874a8bcdb9dd16f5fec7b3e173cae
homepage   : https://github.com/prompt-toolkit/python-prompt-toolkit
license    : BSD-3-Clause
component  : programming.python
summary    : Library for building powerful interactive command lines in Python
description: |
    prompt_toolkit is a library for building powerful interactive command line applications in Python.
builddeps  :
    - python-pytest  # check
    - python-wcwidth # check
rundeps    :
    - python-wcwidth
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
