name       : python-prompt-toolkit
version    : 3.0.38
release    : 13
source     :
    - https://files.pythonhosted.org/packages/source/p/prompt_toolkit/prompt_toolkit-3.0.38.tar.gz : 23ac5d50538a9a38c8bde05fecb47d0b403ecd0662857a86f886f798563d5b9b
homepage   : https://github.com/prompt-toolkit/python-prompt-toolkit
license    : BSD-3-Clause
component  : programming.python
summary    : Library for building powerful interactive command lines in Python
description: |
    prompt_toolkit is a library for building powerful interactive command line applications in Python.
builddeps  :
    - python-pytest  # check
    - python-wcwidth # check
rundeps    :
    - python-wcwidth
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
