name       : python-prompt-toolkit
version    : 3.0.36
release    : 12
source     :
    - https://files.pythonhosted.org/packages/source/p/prompt_toolkit/prompt_toolkit-3.0.36.tar.gz : 3e163f254bef5a03b146397d7c1963bd3e2812f0964bb9a24e6ec761fd28db63
homepage   : https://github.com/prompt-toolkit/python-prompt-toolkit
license    : BSD-3-Clause
component  : programming.python
summary    : Library for building powerful interactive command lines in Python
description: |
    prompt_toolkit is a library for building powerful interactive command line applications in Python.
builddeps  :
    - python-pytest  # check
    - python-wcwidth # check
rundeps    :
    - python-wcwidth
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
