name       : python-prompt-toolkit
version    : 1.0.9
release    : 1
source     :
    - https://pypi.python.org/packages/83/14/5ac258da6c530eca02852ee25c7a9ff3ca78287bb4c198d0d0055845d856/prompt_toolkit-1.0.9.tar.gz : cd6523b36adc174cc10d54b1193eb626b4268609ff6ea92c15bcf1996609599c
license    : BSD-3-Clause
component  : programming.python
summary    : Library for building powerful interactive command lines in Python
description: |
    Library for building powerful interactive command lines in Python
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
    - python-six
    - python-wcwidth
rundeps    :
    - python-six
    - python-wcwidth
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
