name       : python-prompt-toolkit
version    : 3.0.29
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/p/prompt_toolkit/prompt_toolkit-3.0.29.tar.gz : bd640f60e8cecd74f0dc249713d433ace2ddc62b65ee07f96d358e0b152b6ea7
homepage   : https://github.com/prompt-toolkit/python-prompt-toolkit
license    : BSD-3-Clause
component  : programming.python
summary    : Library for building powerful interactive command lines in Python
description: |
    prompt_toolkit is a library for building powerful interactive command line applications in Python.
builddeps  :
    - python-pytest  # check
    - python-six     # check
    - python-wcwidth # check
rundeps    :
    - python-six
    - python-wcwidth
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
