name       : python-prompt-toolkit
version    : 1.0.14
release    : 4
source     :
    - https://github.com/jonathanslenders/python-prompt-toolkit/archive/1.0.14.tar.gz : ac04b23e73a5cf97551d17f4007674262a023e4f574d3c4cfe8c1383ec9764ec
license    : BSD-3-Clause
component  : programming.python
summary    : Library for building powerful interactive command lines in Python
description: |
    Library for building powerful interactive command lines in Python
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - python-six
    - python-wcwidth
rundeps    :
    - python-six
    - python-wcwidth
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
