name       : python-prompt-toolkit
version    : 3.0.30
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/p/prompt_toolkit/prompt_toolkit-3.0.30.tar.gz : 859b283c50bde45f5f97829f77a4674d1c1fcd88539364f1b28a37805cfd89c0
homepage   : https://github.com/prompt-toolkit/python-prompt-toolkit
license    : BSD-3-Clause
component  : programming.python
summary    : Library for building powerful interactive command lines in Python
description: |
    prompt_toolkit is a library for building powerful interactive command line applications in Python.
builddeps  :
    - python-pytest  # check
    - python-wcwidth # check
rundeps    :
    - python-wcwidth
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
