name       : python-prompt-toolkit
version    : 3.0.8
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/p/prompt_toolkit/prompt_toolkit-3.0.8.tar.gz : 25c95d2ac813909f813c93fde734b6e44406d1477a9faef7c915ff37d39c0a8c
homepage   : https://github.com/prompt-toolkit/python-prompt-toolkit
license    : BSD-3-Clause
component  : programming.python
summary    : Library for building powerful interactive command lines in Python
description: |
    Library for building powerful interactive command lines in Python
builddeps  :
    - pkgconfig(python3)
    - python-pytest
    - python-six
    - python-wcwidth
rundeps    :
    - python-six
    - python-wcwidth
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
